universe = vanilla
executable = /archive/home/pulsar/feedforward/2012/05/07/AMPS/run_eleutheria-well.sh
output = /archive/home/pulsar/feedforward/2012/05/07/AMPS/logs/eleutheria.out.$(process)
error = logs/eleutheria.err.$(process)
log = logs/eleutheria.log.$(process)
requirements = Memory >= 3999
concurrency_limits = 40
environment = HOME=/archive/home/pulsar;LD_LIBRARY_PATH=/ldcg/matlab_r2010b/runtime/glnxa64:/ldcg/matlab_r2010b/bin/glnxa64:/ldcg/matlab_r2010b/extern/lib/glnxa64:/ligotools/lib
 
arguments = 932495918 932496512 cache/fileList-DARM-932495918-932496512.txt cache/fileList-NOISE-932495918-932496512.txt
queue
