universe = vanilla
executable = /home/pulsar/feedforward/2012/07/17/AMPS/run_eleutheria-well.sh
output = /home/pulsar/feedforward/2012/07/17/AMPS/eleutheriaLogs/eleutheria.out.$(tagstring)
error = eleutheriaLogs/eleutheria.err.$(tagstring)
log = /usr1/pulsar/eleutheria.dag.log
requirements = Memory >= 3999
environment = HOME=/archive/home/pulsar;LD_LIBRARY_PATH=/ldcg/matlab_r2010b/runtime/glnxa64:/ldcg/matlab_r2010b/bin/glnxa64:/ldcg/matlab_r2010b/extern/lib/glnxa64:/ligotools/lib
notification = never

arguments = $(argList)
queue 1

