universe = vanilla
executable = /archive/home/gmeadors/2012/03/17/AMPS/run_eleutheria-well.sh
output = /archive/home/gmeadors/2012/03/17/AMPS/logs/eleutheria.out.$(process)
error = logs/eleutheria.err.$(process)
log = logs/eleutheria.log.$(process)
requirements = Memory >= 3999
concurrency_limits = 40
environment = HOME=/archive/home/gmeadors;LD_LIBRARY_PATH=/ldcg/matlab_r2011a/runtime/glnxa64:/ldcg/matlab_r2011a/bin/glnxa64:/ldcg/matlab_r2011a/extern/lib/glnxa64:/ligotools/lib
 
arguments = 932495918 932496512 cache/fileList-DARM-932495918-932496512.txt cache/fileList-NOISE-932495918-932496512.txt
queue
