universe = vanilla
executable = /home/pulsar/feedforward/2012/06/19/AMPS/interstitial.py
output = /home/pulsar/feedforward/2012/06/19/AMPS/interstitialLogs/interstitial.out.$(process)
error = interstitialLogs/interstitial.err.$(process)
log = interstitialLogs/interstitial.log.$(process)
requirements = Memory >= 3999

arguments = 9310 cache/interstitialCache-Hoft-931000000-931100000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9311 cache/interstitialCache-Hoft-931100000-931200000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9312 cache/interstitialCache-Hoft-931200000-931300000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9313 cache/interstitialCache-Hoft-931300000-931400000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9314 cache/interstitialCache-Hoft-931400000-931500000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9315 cache/interstitialCache-Hoft-931500000-931600000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9316 cache/interstitialCache-Hoft-931600000-931700000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9317 cache/interstitialCache-Hoft-931700000-931800000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9318 cache/interstitialCache-Hoft-931800000-931900000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9319 cache/interstitialCache-Hoft-931900000-932000000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9320 cache/interstitialCache-Hoft-932000000-932100000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9321 cache/interstitialCache-Hoft-932100000-932200000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9322 cache/interstitialCache-Hoft-932200000-932300000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9323 cache/interstitialCache-Hoft-932300000-932400000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9324 cache/interstitialCache-Hoft-932400000-932500000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9325 cache/interstitialCache-Hoft-932500000-932600000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9326 cache/interstitialCache-Hoft-932600000-932700000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

arguments = 9327 cache/interstitialCache-Hoft-932700000-932800000.txt H 128 /home/pulsar/feedforward/2012/06/19/AMPS/
queue

